<div class="loadingio-spinner-spin-e0gon8taei9">
	<div class="ldio-cosniyqmn05">
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
		<div><div /></div>
	</div>
</div>

<style type="text/css">
	@keyframes ldio-cosniyqmn05 {
		0% {
			opacity: 1;
			backface-visibility: hidden;
			transform: translateZ(0) scale(1, 1);
		}
		100% {
			opacity: 0;
			backface-visibility: hidden;
			transform: translateZ(0) scale(1, 1);
		}
	}
	.ldio-cosniyqmn05 div > div {
		position: absolute;
		width: 12px;
		height: 12px;
		border-radius: 50%;
		background: #1e3150;
		animation: ldio-cosniyqmn05 1s linear infinite;
	}
	.ldio-cosniyqmn05 div:nth-child(1) > div {
		left: 78px;
		top: 54px;
		animation-delay: -0.9s;
	}
	.ldio-cosniyqmn05 > div:nth-child(1) {
		transform: rotate(0deg);
		transform-origin: 84px 60px;
	}
	.ldio-cosniyqmn05 div:nth-child(2) > div {
		left: 73px;
		top: 68px;
		animation-delay: -0.8s;
	}
	.ldio-cosniyqmn05 > div:nth-child(2) {
		transform: rotate(36deg);
		transform-origin: 79px 74px;
	}
	.ldio-cosniyqmn05 div:nth-child(3) > div {
		left: 61px;
		top: 77px;
		animation-delay: -0.7s;
	}
	.ldio-cosniyqmn05 > div:nth-child(3) {
		transform: rotate(72deg);
		transform-origin: 67px 83px;
	}
	.ldio-cosniyqmn05 div:nth-child(4) > div {
		left: 47px;
		top: 77px;
		animation-delay: -0.6s;
	}
	.ldio-cosniyqmn05 > div:nth-child(4) {
		transform: rotate(108deg);
		transform-origin: 53px 83px;
	}
	.ldio-cosniyqmn05 div:nth-child(5) > div {
		left: 35px;
		top: 68px;
		animation-delay: -0.5s;
	}
	.ldio-cosniyqmn05 > div:nth-child(5) {
		transform: rotate(144deg);
		transform-origin: 41px 74px;
	}
	.ldio-cosniyqmn05 div:nth-child(6) > div {
		left: 30px;
		top: 54px;
		animation-delay: -0.4s;
	}
	.ldio-cosniyqmn05 > div:nth-child(6) {
		transform: rotate(180deg);
		transform-origin: 36px 60px;
	}
	.ldio-cosniyqmn05 div:nth-child(7) > div {
		left: 35px;
		top: 40px;
		animation-delay: -0.3s;
	}
	.ldio-cosniyqmn05 > div:nth-child(7) {
		transform: rotate(216deg);
		transform-origin: 41px 46px;
	}
	.ldio-cosniyqmn05 div:nth-child(8) > div {
		left: 47px;
		top: 31px;
		animation-delay: -0.2s;
	}
	.ldio-cosniyqmn05 > div:nth-child(8) {
		transform: rotate(252deg);
		transform-origin: 53px 37px;
	}
	.ldio-cosniyqmn05 div:nth-child(9) > div {
		left: 61px;
		top: 31px;
		animation-delay: -0.1s;
	}
	.ldio-cosniyqmn05 > div:nth-child(9) {
		transform: rotate(288deg);
		transform-origin: 67px 37px;
	}
	.ldio-cosniyqmn05 div:nth-child(10) > div {
		left: 73px;
		top: 40px;
		animation-delay: 0s;
	}
	.ldio-cosniyqmn05 > div:nth-child(10) {
		transform: rotate(324deg);
		transform-origin: 79px 46px;
	}
	.loadingio-spinner-spin-e0gon8taei9 {
		width: 120px;
		height: 120px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-cosniyqmn05 {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-cosniyqmn05 div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
