name: Build And Deploy Pitel API Docs

on:
  push:
    branches: [ 'dev' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Resource
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      
      - name: Install Package
        run: npm install
        
      - name: Build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run build
          cp package.json build
          cp package-lock.json build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: prod
          keep_files: false